In [1]:
import pandas as pd
titanic = pd.read_csv("../data/titanic_propre.csv")
titanic.shape

(889, 11)

In [2]:
ports = pd.DataFrame({
    "embark_town": ["Southampton", "Cherbourg", "Queenstown"],
    "pays": ["Angleterre", "France", "Irlande"],
})
ports

   embark_town        pays
0  Southampton  Angleterre
1    Cherbourg      France
2   Queenstown     Irlande

In [3]:
nb_avant = len(titanic)
nb_avant

889

In [4]:
titanic = titanic.merge(ports, on="embark_town", how="left", validate="many_to_one")
titanic.head()

,survived,sex,age,sibsp,parch,fare,class,who,adult_male,embark_town,alone,pays
0,False,male,22.0,1,0,7.2500,Third,man,True,Southampton,False,Angleterre
1,True,female,38.0,1,0,71.2833,First,woman,False,Cherbourg,False,France
2,True,female,26.0,0,0,7.9250,Third,woman,False,Southampton,True,Angleterre
3,True,female,35.0,1,0,53.1000,First,woman,False,Southampton,False,Angleterre
4,False,male,35.0,0,0,8.0500,Third,man,True,Southampton,True,Angleterre

In [5]:
assert len(titanic) == nb_avant
len(titanic)

889

J’ai joint la table ports à titanic avec how="left" pour garder tous les passagers. J’ai compté les lignes avant et après la jointure et il y en a 889 dans les deux cas

In [6]:
titanic["pays"].value_counts()

pays
Angleterre    644
France        168
Irlande        77
Name: count, dtype: int64

In [7]:
titanic.groupby("pays")["survived"].mean()

pays
Angleterre    0.336957
France        0.553571
Irlande       0.389610
Name: survived, dtype: float64

La majorité des passagers sont partis d’Angleterre (644), puis de France (168) et d’Irlande (77). Les passagers partis de France ont le mieux survécu (55,4 %), sûrement parce que la moitié d’entre eux voyageaient en 1ere classe

In [8]:
ports_sans_queenstown = ports[ports["embark_town"] != "Queenstown"]
ports_sans_queenstown

   embark_town        pays
0  Southampton  Angleterre
1    Cherbourg      France

In [9]:
titanic_base = pd.read_csv("../data/titanic_propre.csv")

In [10]:
jointure_inner = titanic_base.merge(ports_sans_queenstown, on="embark_town", how="inner")
len(jointure_inner)

812

In [11]:
jointure_left = titanic_base.merge(ports_sans_queenstown, on="embark_town", how="left")
len(jointure_left)

889

In [12]:
jointure_left["pays"].isna().sum()

np.int64(77)

J’ai retiré Queenstown de la table ports puis j’ai refait la jointure de deux façons.
Avec how="inner" il ne reste que 812 passagers, les 77 passagers partis de Queenstown ont disparu car leur port n’existe plus dans ports.Avec how="left" les 889 passagers sont toujours là. Les 77 passagers de Queenstown sont gardés, mais leur colonne pays est vide.Inner peut faire perdre des lignes sans prévenir alors que left les garde et montre clairement ce qui manque.