In [1]:
import pandas as pd
import seaborn as sns

taxis = sns.load_dataset("taxis")
taxis.shape

(6433, 14)

In [2]:
taxis.head()

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan

In [3]:
taxis.dtypes

pickup             datetime64[us]
dropoff            datetime64[us]
passengers                  int64
distance                  float64
fare                      float64
tip                       float64
tolls                     float64
total                     float64
color                         str
payment                       str
pickup_zone                   str
dropoff_zone                  str
pickup_borough                str
dropoff_borough               str
dtype: object

In [4]:
taxis["pickup"] = pd.to_datetime(taxis["pickup"])
taxis["dropoff"] = pd.to_datetime(taxis["dropoff"])
taxis.dtypes

pickup             datetime64[us]
dropoff            datetime64[us]
passengers                  int64
distance                  float64
fare                      float64
tip                       float64
tolls                     float64
total                     float64
color                         str
payment                       str
pickup_zone                   str
dropoff_zone                  str
pickup_borough                str
dropoff_borough               str
dtype: object

Dans ma version de seaborn pickup et dropoff sont déjà chargées comme des dates. Je les convertis quand même avec pd.to_datetime pour que le notebook fonctionne aussi si elles arrivent sous forme de texte

In [5]:
taxis["pickup"].min(), taxis["pickup"].max()

(Timestamp('2019-02-28 23:29:03'), Timestamp('2019-03-31 23:43:45'))

Le jeu de données couvre le mois de mars 2019 du 28 février à 23h29 au 31 mars à 23h43.

In [6]:
ca_par_jour = taxis.set_index("pickup").resample("D")["total"].sum()
ca_par_jour

pickup
2019-02-28       6.30
2019-03-01    4213.83
2019-03-02    3319.02
2019-03-03    3027.32
2019-03-04    3269.08
2019-03-05    4377.38
2019-03-06    4673.61
2019-03-07    4115.70
2019-03-08    4524.21
2019-03-09    3785.80
2019-03-10    3198.69
2019-03-11    4021.26
2019-03-12    3875.80
2019-03-13    4868.06
2019-03-14    4742.55
2019-03-15    4030.29
2019-03-16    3836.58
2019-03-17    3469.50
2019-03-18    3258.78
2019-03-19    3963.92
2019-03-20    4522.95
2019-03-21    4355.08
2019-03-22    4245.36
2019-03-23    3355.98
2019-03-24    2616.81
2019-03-25    2877.55
2019-03-26    3366.20
2019-03-27    4417.17
2019-03-28    3886.44
2019-03-29    3790.52
2019-03-30    4004.39
2019-03-31    3108.84
Freq: D, Name: total, dtype: float64

In [7]:
courses_par_jour = taxis.set_index("pickup").resample("D")["total"].count()
courses_par_jour

pickup
2019-02-28      1
2019-03-01    241
2019-03-02    198
2019-03-03    169
2019-03-04    171
2019-03-05    228
2019-03-06    257
2019-03-07    218
2019-03-08    235
2019-03-09    204
2019-03-10    185
2019-03-11    209
2019-03-12    218
2019-03-13    244
2019-03-14    260
2019-03-15    201
2019-03-16    220
2019-03-17    178
2019-03-18    173
2019-03-19    201
2019-03-20    233
2019-03-21    221
2019-03-22    229
2019-03-23    209
2019-03-24    149
2019-03-25    155
2019-03-26    178
2019-03-27    232
2019-03-28    205
2019-03-29    209
2019-03-30    215
2019-03-31    187
Freq: D, Name: total, dtype: int64

en mars 2019, il y a entre 169 et 260 courses par jour pour un chiffre d’affaires d’environ 3 000$ à 4 900$  par jour. Le 28 février n’a qu’une seule course (6,30$) car le jeu de données commence à 23h29 ce jour-là.

In [8]:
taxis["heure"] = taxis["pickup"].dt.hour
taxis[["pickup", "heure"]].head()

               pickup  heure
0 2019-03-23 20:21:09     20
1 2019-03-04 16:11:55     16
2 2019-03-27 17:53:01     17
3 2019-03-10 01:23:59      1
4 2019-03-30 13:27:42     13

In [9]:
courses_par_heure = taxis["heure"].value_counts()
courses_par_heure

heure
18    417
19    406
17    388
20    368
14    360
21    355
16    336
12    334
15    330
10    325
22    321
9     319
13    316
8     313
23    296
11    295
7     221
0     205
6     142
1     110
2     101
3      67
4      57
5      51
Name: count, dtype: int64

L’heure la plus chargée est 18h (417 courses), suivie de 19h et 17h correspondant aux heures de sortie du travail. Les heures les plus calmes sont entre 3h et 5h du matin

In [10]:
taxis["jour_semaine"] = taxis["pickup"].dt.day_name()
taxis[["pickup", "jour_semaine"]].head()

               pickup jour_semaine
0 2019-03-23 20:21:09     Saturday
1 2019-03-04 16:11:55       Monday
2 2019-03-27 17:53:01    Wednesday
3 2019-03-10 01:23:59       Sunday
4 2019-03-30 13:27:42     Saturday

In [11]:
pourboir_par_jour = taxis.groupby("jour_semaine")["tip"].mean().sort_values(ascending=False)
pourboir_par_jour

jour_semaine
Wednesday    2.087329
Thursday     2.062177
Monday       2.027316
Tuesday      2.001370
Friday       1.980108
Sunday       1.908710
Saturday     1.815143
Name: tip, dtype: float64

C’est le mercredi que le pourboire moyen est le plus élevé 2,09 $, et le samedi qu’il est le plus faible 1,82 $.

In [12]:
#calcule de la durée des courses
taxis["duree"] = taxis["dropoff"] - taxis["pickup"]
taxis["duree"].head()

0   0 days 00:06:15
1   0 days 00:07:05
2   0 days 00:07:24
3   0 days 00:25:52
4   0 days 00:09:32
Name: duree, dtype: timedelta64[us]

In [13]:
#transformation de la durée en minutes
taxis["duree_min"] = taxis["duree"].dt.total_seconds() / 60
taxis["duree_min"].head()

0     6.250000
1     7.083333
2     7.400000
3    25.866667
4     9.533333
Name: duree_min, dtype: float64

In [14]:
#voir le resumé des durées 
taxis["duree_min"].describe()

count    6433.000000
mean       14.349617
std        11.643892
min         0.000000
25%         6.500000
50%        10.900000
75%        18.516667
max       107.666667
Name: duree_min, dtype: float64

In [15]:
#verifie si les courses de moins de une minutes sont des erreurs
courses_tres_courtes = taxis[taxis["duree_min"] < 1]
print(len(courses_tres_courtes))
courses_tres_courtes[["pickup", "dropoff", "distance", "total"]].head(10)

72

                 pickup             dropoff  distance   total
42  2019-03-30 23:59:14 2019-03-30 23:59:17      0.00  100.38
88  2019-03-16 05:08:02 2019-03-16 05:08:20      0.07    3.80
120 2019-03-21 17:21:44 2019-03-21 17:21:49      0.00    4.30
400 2019-03-09 17:26:02 2019-03-09 17:26:10      0.90    5.80
458 2019-03-24 01:08:20 2019-03-24 01:08:34      0.02    6.30
491 2019-03-07 07:11:33 2019-03-07 07:11:39      1.60    5.80
622 2019-03-12 19:52:36 2019-03-12 19:52:55      0.00  166.00
624 2019-03-05 09:59:42 2019-03-05 10:00:34      0.31    7.30
644 2019-03-30 21:50:51 2019-03-30 21:51:40      0.30    8.80
670 2019-03-08 04:50:48 2019-03-08 04:51:07      0.00    6.30

In [16]:
#veriffie la distance des courses de plus d'une heure
taxis.sort_values("duree_min", ascending=False)[["duree_min", "distance", "pickup_zone", "dropoff_zone"]].head(5)

       duree_min  distance                        pickup_zone    dropoff_zone
6053  107.666667     22.17  University Heights/Morris Heights  Yorkville East
5567   93.966667     25.51                   Sunset Park West    Saint Albans
5648   89.883333     33.46                      East Flushing             NaN
5833   88.550000     12.79            Queensbridge/Ravenswood       Flatlands
4218   81.533333     26.92                        JFK Airport     Cobble Hill

In [17]:
nb_avant = len(taxis)
taxis = taxis[taxis["duree_min"] >= 1]
print("avant:", nb_avant, "après:", len(taxis))

avant: 6433 après: 6361

j’ai calculé la durée de chaque course en minutes. J’ai trouvé 72 courses de moins d’une minute : la plupart ont une distance nulle et certaines sont impossibles (1,6 mile en 6 secondes). Ce sont des erreurs ou des courses annulées, donc je les ai supprimées (6 433 devient 6 361 courses). Les courses les plus longues jusqu’à 1h48 font entre 12 et 33 miles, elles sont longues mais réelles donc je les ai gardées